version: "3"

services:
  nginx:
    image: ${DOCKERHUB_NAMESPACE}/nginx-router:${TAG}
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client

  client:
    image: ${DOCKERHUB_NAMESPACE}/react-client:${TAG}
    mem_limit: 128m
    hostname: client

  api:
    image: ${DOCKERHUB_NAMESPACE}/node-server:${TAG}
    mem_limit: 128m
    hostname: api
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
    ports:
      - "5000:5000"

  worker:
    image: ${DOCKERHUB_NAMESPACE}/node-worker:${TAG}
    mem_limit: 128m
    hostname: worker
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
